[package]
name = "egui_hooks"
version = "0.1.0"
edition = "2021"
description = "React Hooks like API for egui"
categories = ["gui"]
keywords = ["egui", "hook", "gamedev"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/ryo33/egui_hooks"

[dependencies]
egui = "0.24"
arc-swap = "1.6"
dyn-clone = "1.0"

[dev-dependencies]
eframe = "0.24"
